vim.cmd("set noexpandtab")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=2")
vim.cmd("set smartindent")
vim.cmd("set wildmenu")
vim.cmd("set nocompatible")
vim.cmd("set mouse=a")
vim.g.mapleader = " "
