vim.cmd("set noexpandtab")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=2")
vim.cmd("set smartindent")
vim.cmd("set wildmenu")
vim.cmd("set nocompatible")
vim.cmd("set mouse=a")
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.api.nvim_set_keymap("i", "jj", "<Esc>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>h", "<C-W>h", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>j", "<C-W>j", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>k", "<C-W>k", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>l", "<C-W>l", { noremap = true })
